### ISSUE TITLE
app cannot be installed from the owncloud app store

### ISSUE THREAD

**Issue by xylo** [Patt92/Workin2Gether#1]
At the moment the app cannot be installed from the owncloud app store.

**Comment by Patt92** [comment]
Please retry downloading it again. I changed the zip in the app store. Please provide feedback :-)

**Comment by xylo** [comment]
Thanks.  The installation via the owncloud app store worked now.  But afterwards I was directed to the upgrade page.  I clicked on the upgrade button and got the following error message:

```
OC\DatabaseException: An exception occurred while executing 'SHOW TABLES LIKE 'oc_locks_w2g'': SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error
```

**Comment by xylo** [comment]
A table called oc_locks_w2g doesn't exist in the owncloud database.

When I reload the owncloud page I get the following error message (sorry, message is in German):

Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
Bitte wenden Sie sich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, geben Sie bitte die, unten stehenden, technischen Details in Ihrem Bericht mit an.
Weitere Details können im Serverprotokoll gefunden werden.

Technische Details
Entfernte Adresse: ::1
Anforderungskennung: a+WjbpT9VwursdNZ76Rq
Typ: OC\DatabaseException
Code: 0
Nachricht: An exception occurred while executing 'SHOW TABLES LIKE 'oc_locks_w2g'': SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error
Datei: /home/stefan/programmierung/web/owncloud/owncloud/lib/private/db.php
Zeile: 77

Spur
#0 /home/stefan/programmierung/web/owncloud/owncloud/lib/public/db.php(59): OC_DB::prepare('SHOW TABLES LIK...', NULL, NULL)
#1 /home/stefan/programmierung/web/owncloud/owncloud/apps/files_w2g/appinfo/app.php(33): OCP\DB::prepare('SHOW TABLES LIK...')
#2 /home/stefan/programmierung/web/owncloud/owncloud/lib/private/app.php(139): require_once('/home/stefan/pr...')
#3 /home/stefan/programmierung/web/owncloud/owncloud/lib/private/app.php(120): OC_App::requireAppFile('files_w2g')
#4 /home/stefan/programmierung/web/owncloud/owncloud/lib/private/app.php(98): OC_App::loadApp('files_w2g')
#5 /home/stefan/programmierung/web/owncloud/owncloud/lib/base.php(858): OC_App::loadApps()
#6 /home/stefan/programmierung/web/owncloud/owncloud/index.php(40): OC::handleRequest()
#7 {main}

**Comment by xylo** [comment]
OK, the "SHOW TABLES" command is only supported by mysql but not by sqlite.  That's why it crashes for me.  I will try it mysql.

**Comment by Patt92** [comment]
Yes it is written for mysql. I should add this to the FAQ and app page.

**Comment by xylo** [comment]
With mysql it works now. Thanks!

**Comment by ps-account** [comment]
any chance this app will get postgres support?

**Comment by Patt92** [comment]
I'm thinking about supporting more db types. It just depends on private spare time. Maybe in the next milestone.
