### ISSUE TITLE
info.xml error on Nextcloud 10.0.2

### ISSUE THREAD

**Issue by greavette** [Patt92/Workin2Gether#10]
Hello,

Thanks very much for making this app available!

I'm trying to install it on my Nextcloud version 10.0.2.  But when I enable this App I receive the following error:

"App can't be installed because the version in info.xml is not the same as the version reported from the app store"

What needs to be done to fix this version reported in the info.xml?

Thank you.

**Comment by Patt92** [comment]
Hello Greavette,

that's weird because it isn't published at the app store at all. I'll publish it for fixing this. 
Depends now on https://github.com/nextcloud/app-certificate-requests/pull/54 
If they approve my app, I can fix it in no time.

**Comment by greavette** [comment]
Hello @Patt92 ,

That is weird...I'm sure I saw your Workin2Gether App in the Nextcloud App Store a few days ago too?  

I hope they approve your app.  Much appreciative to you for making this available for all to use.

Thank you.

**Comment by Patt92** [comment]
Shouldn't be there :-)
Did you try installing it manually in Nextcloud or really with app store?
Nextcloud shouldn't support it for now. But I tested the latest current stable with Nextcloud 11.0.2 and it worked out of the box.

**Comment by greavette** [comment]
Yes I did add it manually to my Nextcloud so most likely that's how I see it when I turn on the experimental apps in my Nextcloud.  I'm not able to move to Nextcloud 11 yet (still waiting on nethserver to upgrade PHP for me) so for now I'm using Nextcloud 10.0.2.  Will your Workin2Gether App work with my version of Nextcloud?

Is there something I can change in the info.xml to allow me to add it to my version of Nextcloud?

Thank you.

**Comment by Patt92** [comment]
where did you get the version? 
If it is from the OC app store it should contain a wrong info.xml.
I recommend cloning the github repo to the apps folder checking that the folder is properly located.
Example for the cloning: git clone https://github.com/Patt92/Workin2Gether.git 

Use the OCC CLI in your nextcloud root directory (search for the occ file) and execute this (web-user depends on your webserver. In my case apache2):
sudo -u www-data /usr/bin/php occ app:enable workin2gether

What are your server specs?

**Comment by greavette** [comment]
Hi @Patt92, I did a git clone from - https://github.com/Patt92/Workin2Gether. 

I cloned this to my Apps folder using the exact instruction you suggested.  

My server is a distro called nethserver from which I can install Nextcloud.  nethserver is based on CentOS 7. nethserver uses Apache to serve up Nextcloud.   I'm thinking the instruction you've provided is probably for debian/ubuntu.  Would you know the instruction I need to use for CentOS?

Thank you.

**Comment by greavette** [comment]
I'm digging a bit more into this and found this page to help me with using occ from CentOS:  https://docs.nextcloud.com/server/9/admin_manual/configuration_server/occ_command.html

When I issue the occ command to list all my apps Workin2gether doesn't show up.  Yet I do have the Workin2gether app folder and there are files in it (from the git clone I did).

**Comment by greavette** [comment]
Here's more information for you @Patt92 

Now I see where I saw the app store mentioned.  I enabled experimental apps in my nextcloud and sure enough your app showed up under Productivity.  I confirmed that it wasn't just me that was seeing it there as another user on the nethserver forum also could see.  But when we tried to enable your app we get the error message:
"App can't be installed because the version in info.xml is not the same as the version reported from the app store"

I know you said it's not on the App Store...but I tell you, both myself and another person had it available but we could't install it.

So this is the instruction that got things working for your App on our Nextcloud version 10.0.2:

cd /var/www/html/nextcloud/apps/
wget https://github.com/Patt92/Workin2Gether/releases/download/0.9.0.1/files_w2g.tar.gz
tar -xvzf files_w2g.tar.gz
rm files_w2g.tar.gz
sudo -u apache /usr/bin/php /var/www/html/nextcloud/occ app:enable files_w2g

Now I have Workin2gether on my Nextcloud again.  :)

**Comment by greavette** [comment]
You can find the thread here on the nethserver website.  Marc found the answer so all credit goes to him and not me with finding the solution.

Thanks.

**Comment by Patt92** [comment]
Hello @greavette ,

brilliant. Actually everything what Marc was telling on http://community.nethserver.org/t/assistance-with-adding-experimental-app-to-nethserver/6209/11 was right. He also pointed out, that it's recommended to use the git clone instead of the latest release. It has no major changes, which could cause an issue, but the app folder/name/namespace will be used in future. I don't know what happens, if I publish an update and you're using still the files_w2g folder.

Please be careful, when using the rm -r commands below! check it double or copy it from here.

sudo -u apache /usr/bin/php /var/www/html/nextcloud/occ app:disable files_w2g
cd /var/www/html/nextcloud/apps/
rm -r files_w2g
git clone "https://github.com/Patt92/Workin2Gether.git"
mv Workin2gether/workin2gether ./
rm -r Workin2gether
sudo -u apache /usr/bin/php /var/www/html/nextcloud/occ app:enable workin2gether

Anyway it should be closed for now. The experimental release in nextcloud seems to be the owncloud release, which isn't uptodate
