### ISSUE TITLE
NextCloud 12

### ISSUE THREAD

**Issue by putt1ck** [Patt92/Workin2Gether#11]
App reports as not compatible with NC12, which is now available on the upgrade channel. Happy to test if it does really work or not.

**Comment by Patt92** [comment]
change the following line inside workin2gether/appinfo/info.xml
`<nextcloud min-version="9" max-version="11.9"/>`

to
`<nextcloud min-version="9" max-version="12.9"/>`

**Comment by putt1ck** [comment]
easy fix :)

**Comment by Patt92** [comment]
Yep, mostly independent to Nextcloud functions :-)
I will push the update 0.9.4 soon
