### ISSUE TITLE
Change from Username to Full name

### ISSUE THREAD

**Issue by greavette** [Patt92/Workin2Gether#13]
Hello,

I'm using Nextcloud 11.0.3 with LDAP (nethserver) and when I install your Workin2Gether module to have our users lock files to denote they are being worked on, the locked by message shows the Username.  In an LDAP environment the Username is not a human readable name but looks like a GUID (something like - 1CCDB02D-84CF-7062-BD82-8I726C188D69).

I would like to suggest you use Full name instead of Username to show who has locked a file so it will be human readable.

Thank you.

**Comment by Patt92** [comment]
This is not related to the app. You have to properly configure LDAP to use samAccountName as user property. The username is used by the OC/NC Api. If your Server setup is faulty, so the app is. If you would check it by yourself, you'd notice, that there are settings in the admin panel for changing between the username and the displayname. Anyway, fix your setup.
