### ISSUE TITLE
Respect Nextcloud Groupfolders and provide options

### ISSUE THREAD

**Issue by radiantwave** [Patt92/Workin2Gether#15]
Locking Groupfolders created by this Nextcloud app: https://github.com/nextcloud/groupfolders shouldn't be possible or it should be configurable.

**Comment by putt1ck** [comment]
to clarify, you want it to not to be possible to lock groupfolders (and possibly make it an option to do so in admin config)?

**Comment by putt1ck** [comment]
@dan-nkl bump...

**Comment by putt1ck** [comment]
Added as an issue on fork here:

https://github.com/newroco/W2G2/issues/3

**Comment by putt1ck** [comment]
Fixed with not allowing locks on group folders (only contents thereof)
