### ISSUE TITLE
Work with Postgresql

### ISSUE THREAD

**Issue by MikeyG** [Patt92/Workin2Gether#16]
The FAQ says the app works with mySQL.  I use Postgres on two production systems, when will it work with Postgresql?

**Comment by Patt92** [comment]
The app uses standard sql statements, so it should work.  Refer to https://github.com/Patt92/Workin2Gether/issues/3#issuecomment-193238441 
You can enable the app, if it doesn't work, remove it from the apps folder or disable it via OCC or DB.
I don't have a Postgresql test server, so I can't confirm, but testers reported it working
