### ISSUE TITLE
Crash on start with An exception occurred while executing 'CREATE table oc_locks_w2g

### ISSUE THREAD

**Issue by nconder** [Patt92/Workin2Gether#17]
Please see ticket for details https://github.com/nextcloud/server/issues/7191

**Comment by Patt92** [comment]
Please refer to https://github.com/Patt92/Workin2Gether/issues/14 
A faulty DB setup can cause this

**Comment by nconder** [comment]
Humm, dont think I have a faulty DB setup things run perfectly fine without this app and have been for a very long time without error. If I add the app this error occurs and when I delete it everything is back to normal. Maybe the app has not accounted for something or you can point me to what fault could possible cause this. The user running NextCloud has DB owner permissions and it seem to be this app that is trying to create the table referenced in the error that will not create. Has this been tested with MariaDB?

**Comment by Patt92** [comment]
It‘s clearly written in your log entry...

Specified key was too long; max key length is 767 bytes

follow the issue, I replied and change the DB configuration. With a non modded MySQL instance, it would have worked. It‘s caused by the MariaDB default config

**Comment by nconder** [comment]
Thanks @Patt92 for taking some time and explaining in a little more detail.
