### ISSUE TITLE
Error after activation / NC not reachable after this error!

### ISSUE THREAD

**Issue by BurtGummer** [Patt92/Workin2Gether#20]
Hello,

after i klick "activate" in Apps i got this error: "ehler: Diese App kann nicht aktiviert werden, da sie den Server instabil macht." (yes, without "F") In english: "Error: This app cannot be activated because it makes the server unstable."

I use NC 12.0.3 on Debian Stretch 64bit.

And then i was shocked, because NC was not more reachable:

https://github.com/nextcloud/server/issues/7191

i have not installed this addon, but it crashes my nc! Bad... **careful everyone!**

The fix is, delete the app-folder, for example:

/var/www/html/nextcloud/apps/workin2gether/

**Comment by ovpc** [comment]
Were did you install from?
No such workin2gether/ app listed in my NCP's /var/www/html/nextcloud/apps/
![ls-var-www-html-nextcloud-apps-workin2gether-not-listed](https://user-images.githubusercontent.com/8775469/34613475-3c564500-f22e-11e7-8a05-0246cc03c434.png)

**Comment by BurtGummer** [comment]
I have

  'appstore.experimental.enabled' => true,

in my config.php and install the app over the appstore.
 
I have set it to false, but i can actvivate the app nevertheless, maybe because it was already activated,

**Comment by putt1ck** [comment]
You can disable any app that causes an issue at the command line 
 sudo -u www-data php /var/www/nextcloud/occ app:disable

What version of w2g do you have?

**Comment by Patt92** [comment]
Yeah obviously wrong configured mariadb/mysql caused a serverside crash. After a log check, you should have seen, what was wrong. It's not cautious to proper installed servers
