### ISSUE TITLE
Database access failure with PostgreSQL 9.4

### ISSUE THREAD

**Issue by waebbl** [Patt92/Workin2Gether#3]
I just installed owncloud, when I administer basic settings and activate the Workin2Gether app, I get an internal server. Looking at my database logs, there's some
syntax error at or near ""LIKE""",,,,,,"SHOW TABLES LIKE 'oc_locks_w2g'"
I found, you're using the SHOW TABLES statement, within your prepare function in the template/admin.php script. The SHOW not being a standard SQL statement, but rather an extension, which is interpretend differently by mysql and postgresql. For postgresql, SHOW is used to ask the server for runtime parameters and can not be used the way it's done in mysql.
See http://www.postgresql.org/docs/9.4/static/sql-show.html for an explanation of this. Activation of Workin2Gether breaks the installation of my 8.2.2 owncloud installation, making the cloud inaccessible.

**Comment by Patt92** [comment]
It's really getting boring, to answer the question everytime again:

Please read the owncloud app description:
https://apps.owncloud.com/content/show.php/Workin2gether+%28Lock+files+in+WebUI%29?content=164016 

There is no PostgreSQL support

Supported: Owncloud 6-8.2.x
Databases: MySQL only

**Comment by ghost** [comment]
@Patt92 Just had a user at IRC asking the same. You could add something like:

```
    <dependencies>
        <database>mysql</database>
   </dependencies>
```

to your appinfo/info.xml . Then the app won't be installable on other database types but i don't know if this is supported by all oC versions you're supporting.

See https://doc.owncloud.org/server/8.2/developer_manual/app/info.html for some more possibilities for dependencies.

**Comment by Patt92** [comment]
that's a useful hint, it will be added to the next release.

**Comment by Patt92** [comment]
updated.

**Comment by ghost** [comment]
Nice. Hope that saves you from some trouble / bugreports.

**Comment by Patt92** [comment]
I changed the pre check. Can anyone confirm the PostgreSQL support with the current beta:
https://cloud.bito.com/index.php/s/TFjoxb8IiYelu1c

**Comment by Patt92** [comment]
Updated: https://cloud.bito.com/index.php/s/kiW9HKplQZ3O9WN
should be now one error until the fix

**Comment by putt1ck** [comment]
Happy to test, struggling to see how to. Can someone point me at the documentation for how to add a new/beta app? I've looked without success for documentation, and tried the simple download/extract - but the only version listed is the 8.2.4 version - trying to enable that gets with the download extracted to the apps directory gets "App directory already exists".

**Comment by Patt92** [comment]
You have to install it manually. Put the content of the zip (files_w2g folder) in your app directory. Replace the existing app.

**Comment by putt1ck** [comment]
I did:

delete existing folder
unzip download
- expected to "see" the app either in admin section or as user and did not

delete folder
click enable for listed 8.2.4 version (ignore error regarding MySQL dependency)
unzip download, replacing existing files
- expected to "see" the app either in admin section or as user and did not

checked permissions etc.. Is there something else I have to change?

**Comment by Patt92** [comment]
Which one did you download? There shouldn't be the dependency of MySQL. Are you sure, that you imported the correct app?
https://cloud.bito.com/index.php/s/kiW9HKplQZ3O9WN

**Comment by putt1ck** [comment]
MySQL error was from clicking enable in the Apps view as an admin, prior to unzipping download. If download already unzipped and click enable I get "App directory already exists".

**Comment by Patt92** [comment]
what's your system?
1. Delete apps/files_w2g (if exist) in your owncloud instance
2. Copy or download the zip to the server
3. Unzip
4. move the files_w2g (got from the zip) to the apps folder
5. Check if app enabled, if not, enable it
If you get an error after enabling, please tell me

**Comment by putt1ck** [comment]
Ok, having done that before, this time I went trawling through all the apps list and eventually found a second listing for the app, away from the expected productivity category. Enabling gets this error message:

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'CREATE table oc_locks_w2g(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255)) DEFAULT CHARACTER SET=utf8 DEFAULT COLLATE=utf8_bin': SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "DEFAULT" LINE 1: ...DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255)) DEFAULT CH... ^

**Comment by Patt92** [comment]
Could you try something:

Change line 34 in apps/files_w2g/appinfo/app.php

From:
        if(!\OC::$server->getDatabaseConnection()->tableExists( app::table )){
                $db_exist = \OCP\DB::prepare("CREATE table _PREFIX_" . app::table . "(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255)) " . app::charset);

TO:
        if(!\OC::$server->getDatabaseConnection()->tableExists( app::table )){
                $db_exist = \OCP\DB::prepare("CREATE table _PREFIX_" . app::table . "(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255))");

**Comment by putt1ck** [comment]
Ok, tried that and got this log entry on accessing the web interface:

{"reqId":"CWzLW8AbUOUtrQkAICXc","remoteAddr":"xxxxx","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\TableExistsException\",\"Message\":\"An exception occurred while executing 'CREATE table PREFIXlocks_w2g(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255))':\n\nSQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \\"prefixlocks_w2g\\" already exists\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'CREATE table PR...', Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \\/var\\/www\\/owncloud\\/apps\\/files_w2g\\/appinfo\\/app.php(37): OC_DB_StatementWrapper->execute()\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(160): require_once('\\/var\\/www\\/ownclo...')\n#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(141): OC_App::requireAppFile('files_w2g')\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(118): OC_App::loadApp('files_w2g')\n#7 \\/var\\/www\\/owncloud\\/lib\\/base.php(835): OC_App::loadApps()\n#8 \\/var\\/www\\/owncloud\\/index.php(39): OC::handleRequest()\n#9 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractPostgreSQLDriver.php\",\"Line\":78}","level":3,"time":"2016-03-07T12:40:23+00:00"}

**Comment by Patt92** [comment]
looking at this log, it seems the table already exists. Can you delete it?
It's named oc_locks_w2g. Also ensure nobody is accessing Owncloud at the same time.
What happens if you reload the cloud? Don't press F5, open it again.

**Comment by Patt92** [comment]
I have updated the initializing of the db table.
grab the newest master https://github.com/Patt92/Workin2Gether/archive/master.zip 
It contains the current files_w2g app with the failsave fix and the correct syntax. I checked it out with 
MySQL and everything works smoothly, so it should now also for PostgreSQL.
We seem to get to the final

**Comment by putt1ck** [comment]
All works now, thanks :)

**Comment by Patt92** [comment]
Sounds good :-)
would you mind checking, if special characters like é or ä ö ü in filenames are working, since I removed the charset part. HTML-encode should make the deal, but just to get sure.

Cheers,

**Comment by putt1ck** [comment]
Created  file Liberté.odt, uploaded, shared, locked; logged in as new user, shared doc appears and shows as locked correctly. I can unlock as either user (wondering, should the user that didn't lock a file be able to unlock without some sort of warning?)

**Comment by Patt92** [comment]
Check the admin settings, you can enable this behavior :-)

**Comment by putt1ck** [comment]
Nice tip, but selecting "admin" area got me an error, with this in the log:

{"reqId":"2jIpZaXq1GkSpKPcu8GG","remoteAddr":"xxxx","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'SHOW TABLES LIKE 'oc_locks_w2g'':\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \\"LIKE\\"\nLINE 1: SHOW TABLES LIKE 'oc_locks_w2g'\n                    ^\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SHOW TABLES LIK...', Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \\/var\\/www\\/owncloud\\/apps\\/files_w2g\\/templates\\/admin.php(21): OC_DB_StatementWrapper->execute()\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/template\\/base.php(160): include('\\/var\\/www\\/ownclo...')\n#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/template\\/base.php(138): OC\\Template\\Base->load('\\/var\\/www\\/ownclo...')\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/template.php(211): OC\\Template\\Base->fetchPage()\n#7 \\/var\\/www\\/owncloud\\/apps\\/files_w2g\\/admin.php(8): OC_Template->fetchPage()\n#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(728): include('\\/var\\/www\\/ownclo...')\n#9 \\/var\\/www\\/owncloud\\/settings\\/admin.php(153): OC_App::getForms('admin')\n#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/ownclo...')\n#11 [internal function]: __lambda_func(Array)\n#12 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/router.php(291): call_user_func('?lambda_1411', Array)\n#13 \\/var\\/www\\/owncloud\\/lib\\/base.php(851): OC\\Route\\Router->match('\\/settings\\/admin')\n#14 \\/var\\/www\\/owncloud\\/index.php(39): OC::handleRequest()\n#15 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractPostgreSQLDriver.php\",\"Line\":66}","level":3,"time":"2016-03-07T13:25:34+00:00"}

**Comment by Patt92** [comment]
There you are, sorry I forgot that there was the same statement ^^'
https://github.com/Patt92/Workin2Gether/archive/master.zip
Update o/

**Comment by putt1ck** [comment]
Ok, that clears the error, and the admin settings appear, but it won't save them. Making any change gets errors like this:
"app":"index","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'INSERT INTO oc_appconfig(appid,configkey,configvalue) value('files_w2g',?,?)' with params [\\"suffix\\", \\"rule_displayname\\"]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \\"value\\"\nLINE 1: ...RT INTO oc_appconfig(appid,configkey,configvalue) value('fil...\n                                                             ^\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...', Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \\/var\\/www\\/owncloud\\/apps\\/files_w2g\\/ajax\\/update.php(24): OC_DB_StatementWrapper->execute(Array)\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/ownclo...')\n#5 [internal function]: __lambda_func(Array)\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/router.php(291): call_user_func('?lambda_1783', Array)\n#7 \\/var\\/www\\/owncloud\\/lib\\/base.php(851): OC\\Route\\Router->match('\\/apps\\/files_w2g...')\n#8 \\/var\\/www\\/owncloud\\/index.php(39): OC::handleRequest()\n#9 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractPostgreSQLDriver.php\",\"Line\":66}","level":3,"time":"2016-03-07T14:05:44+00:00"}

**Comment by Patt92** [comment]
Please update:https://github.com/Patt92/Workin2Gether/archive/master.zip
I made a SQL syntax error, I couldn't reproduce it, because I already have the values

**Comment by putt1ck** [comment]
All sorted now, looks good. Key collaboration feature, would classify it under "productivity" on that basis.

**Comment by Patt92** [comment]
Already done in the appstore :-)
Glad, it's working now
