### ISSUE TITLE
Too much space used by text in user inteface

### ISSUE THREAD

**Issue by danielepercivaldi** [Patt92/Workin2Gether#5]
I think it could be better if:
- the color you set in admin panel is used ONLY to colorize the padlock
- the status of a file is identified by the color of the padlock (grey/set color, NO DESCRIPTION)
- you show ONLY the name of the user who locked the file near the colorized padlock

What do you think about it?

**Comment by Patt92** [comment]
The idea of a colorized padlock is a smart idea, it would get rid of the chaotic design. Would be better to ask some other users. I will think about it.

**Comment by Patt92** [comment]
The SVG behavior is strange in OC, so I removed the text, when not locked. The space is fine that way.
