### ISSUE TITLE
Major performance problems

### ISSUE THREAD

**Issue by xylo** [Patt92/Workin2Gether#6]
I'm using working2gether in an owncloud instance with 11500 files and 420 directories and I discovered major performance problems with the plugin.  When I open the main page (files) it takes more than 2 minutes to get completely loaded.  The webbrowser waits around 98% of this time for the respones of getcolor.php and working2gether.php.
The getcolor.php causes 6.8s + 2.7s waiting tiem while working2gether.php takes around 5 seconds for each file/directory in the directory view.
The more files you have in an directory the longer the page load will be.  In case of my root directory with 25 sub directories it takes more than 2 minutes which makes it very very hard to work with ownlcoud.

It seems there are some O(n) or O(n²) algorithms in the plugin.  Do you think you can replace them by some O(1) or O(log n) ones?.

**Comment by Patt92** [comment]
On my cloud. getcolor causes a waiting time of one time 112ms and 40ms. I don't know how you would be able to increase it to 6000%...
Please provide any system infos, this seems to be a hosting issue.

I don't use any algos, which functions do you mean?

**Comment by xylo** [comment]
My ownCloud instance is running on a 64 bit Linux server with PHP 4.6 running as fastcgi process.  I have the feeling that PHP parses the whole owncloud project when a page request comes in and enabling OPCache did not really help.  That's why any AJAX request takes ages.  Since your add-on is performing one AJAX request per file shown in the file list, loading the whole page takes unfortunately over 2 minutes with our (non-perfect) PHP setup.  Thus, we disabled your add-on for the moment and we try to enable APCu.  Maybe that helps.

However, wouldn't it be better to call working2gether.php only once?  A lot of actions (checking user permissions, requesting the database, joining tables, ...) is done multiple times (for each AJAX call), although this could be done at once and would be much more efficient.

**Comment by jgrete** [comment]
Hello,
after a long lasting search I've found, that Working2Gether renders my Nextcloud 12 installation unusable. Like @xylo described it, it takes minutes to get the contents of the next directory level - especially on external storage. Also, I've problems to log off (!) - but this might be a side effect. I'll provide logs as soon as I got time to activate working2gether again and see what happens.
My system info:

Speicher
Nutzer: 22
Dateien: 2321931
PHP
Version: 5.6.30

Arbeitspeichergrenzwert: 536870912
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 511 MB

Datenbank
Art: mysql
Version: 10.1.22
Größe: 1.1 GB

I really would like to see this app working, but for now I cannot use it

Regards
Jürgen

**Comment by patschi** [comment]
I fully can agree. Even with PHP 7.0 (which has a noticable performanceboost over 5.6) I experience a performance drop even with about 20 files in the directory.

Good plugin idea, but it should be much more performance-focused, specially for bigger environments. One potential issue about this performance issue may the heavy amount of AJAX requests this app does trigger: It seems to make one request for each file in the directory, to determine the lock status.

**Comment by Patt92** [comment]
Noted, will get fixed soon

**Comment by Patt92** [comment]
1-2 calls for all files now. Anyone up for checking?
@patschi your issue is fixed.
@jgrete logging of won't get prevented from my app, check your setup => not related
=> Please check the performance now, should be better. Other issues may be setup related.

**Comment by jgrete** [comment]
@Patt92 new version is doing well!. Logging-off problem was a side effect. Thanks for the fast response!
