### ISSUE TITLE
ownCloud 9.0.0 or lower is required.

### ISSUE THREAD

**Issue by Koblenz** [Patt92/Workin2Gether#8]
I have installed OC 9.0.1, i installed the app, but can´t activate it.

Diese App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
ownCloud 9.0.0 or lower is required.

**Comment by Patt92** [comment]
Hello,

the for better maintenance, the app approval team suggested me to set a maximal version for each release. You can enable the app with a higher version, if you change the max version in the file appinfo/info.xml.

change max-version="9.0.0"
to          max-version="9.0.1"

Please give me a feedback, if the app works with 9.0.1, then I will push the changed max-version to the  repo. 

If you like the app, I'd be happy about a rating in the OC app store :-)

Cheers,

Patrick

**Comment by Koblenz** [comment]
I changed the info.xml to 9.0.1, i can activate the app it, but did not working.
I dont see the settings for w2g in the admin panel, there´s no option for lock/unlock files and folders. 

I upgraded from OC8.2.3 to OC 9.0.1 (In 8.2.3 it is working).

(Rated it, very good solution for Company´s with collab.)
